version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - FIXER_PASSWORD=YourFixIOPassword
      - OER_PASSWORD=YourOpenExchangeRatePassword
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=exchange-rate-postgres